# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Negot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_time', models.DateTimeField(auto_now=True)),
                ('checkin_date', models.DateField()),
                ('chechout_date', models.DateField()),
                ('destination', models.CharField(max_length=254)),
                ('guest_num', models.IntegerField(default=1)),
                ('num_of_results', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Negot.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
