# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negot', '0003_auto_20160403_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='chechout_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='search',
            name='checkin_date',
            field=models.DateField(),
        ),
    ]
