# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negot', '0005_auto_20160409_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='airBnbId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
