# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negot', '0006_auto_20160409_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='minimum_nights',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='number_of_reviews',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='review_scores_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
